site_name: Le Bastion
site_description: "Le Bastion est un site web créé avec MkDocs Material thèmes servant de PKM."
site_url: https://jeoste.github.io/le-bastion
repo_url: https://github.com/jeoste/le-bastion
repo_name: jeoste/le-bastion
nav:
  - Home: index.md
  - Admonition: admonition.md
  - Private:
    - Clients:
      - Uperio: uperio.md
      - Alliance Marine: alliance-marine.md
  - About: about.md
  - Login: login.md
theme: 
  name: material
  icon:
    repo: fontawesome/brands/git
  features:
    - navigation.footer
  logo: assets/shield-logo.png
  favicon: assets/favicon.ico
  font:
    text: Inter
    code: Roboto Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Dark mode
      primary: orange
      accent: cyan

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: cyan
      accent: orange

plugins:
  - search
  - blog:
      blog_dir: .   
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      post_url_format: "{slug}"
  - rss

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: material/github
      link: https://github.com/jeoste
    - icon: material/web
      link: https://linktr.ee/jeoste

hooks:
  - hooks/socialmedia.py

copyright: Copyright &copy; 2024 Jeoffrey Stéphan